# ISA 414 - Managing Big Data
## Lecture 4 - Preliminaries (Part III): Advanced Variable Types

#### Slide 6

In [1]:
# lists are created using square brackets

# first example
beatles_list = ["Paul", "John", "Ringo", "George"]
beatles_list

['Paul', 'John', 'Ringo', 'George']

In [2]:
# a list can contain different data types

# second example
mixed_list = ["Paul", 1, "John", True, "Ringo", 2.0, "George"]
mixed_list

['Paul', 1, 'John', True, 'Ringo', 2.0, 'George']

In [3]:
# obtain the length of a list using the len() function

# third example
len(mixed_list)

7

#### Slide 7

In [4]:
# first example: accessing the *third* element of a list
# the first item has index 0
print(mixed_list[2])

John

In [5]:
# second example
# negative indexing
print(mixed_list[-1])

George

#### Slide 8

In [6]:
# first code
# a range of elements to be retrieved
# slicing notation: [start:end:step]
mixed_list[0:6:2]

['Paul', 'John', 'Ringo']

In [7]:
# second code
# by leaving out the start (or end) value, the range will start (or end) at the first (or last) item
# this code starts at the second item
mixed_list[2:]

['John', True, 'Ringo', 2.0, 'George']

In [8]:
# third code
# this code stop sat the 5th item
mixed_list[:5]

['Paul', 1, 'John', True, 'Ringo']

#### Slide 9

In [9]:
# first code
# adds an element to the end of the list
mixed_list.append("ISA 414")
mixed_list

['Paul', 1, 'John', True, 'Ringo', 2.0, 'George', 'ISA 414']

In [10]:
# add a list to a list
# mixed_list.append(["ISA 414", "ISA 365"])
# mixed_list

In [11]:
# second code
# one can concatenate two lists by summing them
combined_list = beatles_list + mixed_list
combined_list

['Paul',
 'John',
 'Ringo',
 'George',
 'Paul',
 1,
 'John',
 True,
 'Ringo',
 2.0,
 'George',
 'ISA 414']

#### Slide 10

In [12]:
# removing elements
# combined_list.pop(-1)
# combined_list

In [13]:
# change the value for a specific element in a list
example_list = [1,2,3]
example_list[0] = 10
example_list

[10, 2, 3]

In [14]:
# if i want to add an element to the start of  a list
example_list_new = ["one"]
example_list_final = example_list_new + example_list
example_list_final

# or
# example_list = ["one"] + example_list

['one', 10, 2, 3]

#### Slide 11

In [15]:
# first code
# looping over a list of items
for value in combined_list:
    print(value)

Paul
John
Ringo
George
Paul
1
John
True
Ringo
2.0
George
ISA 414

In [16]:
# second code
# looping through index numbers
for index in range(len(combined_list)):
    print(combined_list[index])

Paul
John
Ringo
George
Paul
1
John
True
Ringo
2.0
George
ISA 414

#### Slide 12

In [17]:
# create loops to add elements to a list
string_list = []
for value in combined_list:
    if type(value) == str:
        string_list.append(value)

string_list

['Paul',
 'John',
 'Ringo',
 'George',
 'Paul',
 'John',
 'Ringo',
 'George',
 'ISA 414']

#### Slide 13

In [18]:
# first code
# list comprehension offers a shorter and more efficient way of creating a new list
string_list = [value for value in combined_list if type(value) == str]
string_list

['Paul',
 'John',
 'Ringo',
 'George',
 'Paul',
 'John',
 'Ringo',
 'George',
 'ISA 414']

In [19]:
# second code
# note that the syntax changes if there is an else statement
     # printing 'none' for values that aren't str
another_list = [value if type(value) == str else None for value in combined_list]
another_list

['Paul',
 'John',
 'Ringo',
 'George',
 'Paul',
 None,
 'John',
 None,
 'Ringo',
 None,
 'George',
 'ISA 414']

#### Slide 15 - make sure you install pandas first by running *pip install pandas* below (note the % symbol)

Note: The % symbol is used to run commands that are not part of the Python programming language. Here, we are invoking an application called `pip`, which is external to Python, and asking it to install the `pandas` module

In [20]:
%pip install pandas --upgrade

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\carothlj\appdata\roaming\python\python313\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\python\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\python\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\python\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Note: The argument of `DataFrame` is a dictionary (more on that in the future)

In [21]:
import pandas

# create a data frame with a single column
# syntax: {"col_1_name": list, "col_2_name":list, ...}
df = pandas.DataFrame({"New":another_list, 
                       "Old":combined_list})

# printing df
df

        New      Old
0      Paul     Paul
1      John     John
2     Ringo    Ringo
3    George   George
4      Paul     Paul
5       NaN        1
6      John     John
7       NaN     True
8     Ringo    Ringo
9       NaN      2.0
10   George   George
11  ISA 414  ISA 414

#### Slide 16

In [22]:
# first code
# unique identifier of the row
df["New"]

0        Paul
1        John
2       Ringo
3      George
4        Paul
5         NaN
6        John
7         NaN
8       Ringo
9         NaN
10     George
11    ISA 414
Name: New, dtype: str

In [23]:
# second code
# accessing columns by name
df[["New", "Old"]]

        New      Old
0      Paul     Paul
1      John     John
2     Ringo    Ringo
3    George   George
4      Paul     Paul
5       NaN        1
6      John     John
7       NaN     True
8     Ringo    Ringo
9       NaN      2.0
10   George   George
11  ISA 414  ISA 414

#### Slide 17

In [24]:
# first code
# accessing rows and/or colomn by location
df.iloc[:,1]

0        Paul
1        John
2       Ringo
3      George
4        Paul
5           1
6        John
7        True
8       Ringo
9         2.0
10     George
11    ISA 414
Name: Old, dtype: object

In [25]:
# second code
df.iloc[[0, 2], :]

     New    Old
0   Paul   Paul
2  Ringo  Ringo

In [26]:
print(df)

        New      Old
0      Paul     Paul
1      John     John
2     Ringo    Ringo
3    George   George
4      Paul     Paul
5       NaN        1
6      John     John
7       NaN     True
8     Ringo    Ringo
9       NaN      2.0
10   George   George
11  ISA 414  ISA 414

In [27]:
# third code
df.iloc[2,1]

'Ringo'

In [28]:
# fourth code
df.iloc[-3,-1]

2.0

In [29]:
# fifth code
df.iloc[1::2,:]

        New      Old
1      John     John
3    George   George
5       NaN        1
7       NaN     True
9       NaN      2.0
11  ISA 414  ISA 414

#### Slide 29

In [30]:
import pandas 
web_data = pandas.read_csv("web_log.csv")
web_data

          City        Client_IP   Country_Name   Latitude   Longitude
0    Singapore  128.199.234.236      Singapore   1.293100  103.855797
1    Singapore  128.199.234.236      Singapore   1.293100  103.855797
2    Singapore  128.199.234.236      Singapore   1.293100  103.855797
3    Singapore  128.199.234.236      Singapore   1.293100  103.855797
4    Singapore  128.199.234.236      Singapore   1.293100  103.855797
..         ...              ...            ...        ...         ...
994    Ashburn     54.227.93.32  United States  39.043701  -77.487503
995    Ashburn     54.227.93.32  United States  39.043701  -77.487503
996    Ashburn     54.227.93.32  United States  39.043701  -77.487503
997    Ashburn     54.227.93.32  United States  39.043701  -77.487503
998    Ashburn     54.227.93.32  United States  39.043701  -77.487503

[999 rows x 5 columns]

#### Slide 30

In [33]:
web_data["Country_Name"].value_counts()

Country_Name
India             357
Thailand          232
United States     190
Spain              93
China              72
Singapore          48
Israel              4
Japan               1
Czech Republic      1
Italy               1
Name: count, dtype: int64

#### Slide 31

In [35]:
results = web_data["Country_Name"].value_counts()

results.to_csv("ftable.csv")